/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author 824114192
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/icone.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        Alterar = new javax.swing.JMenuItem();
        Fornecedores = new javax.swing.JMenu();
        cadastrarFornecedores = new javax.swing.JMenuItem();
        alterarFornecedor = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenu();
        procurarProdutos = new javax.swing.JMenuItem();
        excluirProdutos = new javax.swing.JMenuItem();
        Relatorio = new javax.swing.JMenu();
        Days = new javax.swing.JMenuItem();
        Years = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu ");
        setMinimumSize(new java.awt.Dimension(650, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(55, 93, 10));
        jDesktopPane1.setForeground(new java.awt.Color(55, 93, 10));
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 640, 330);

        jMenuBar1.setBackground(new java.awt.Color(252, 233, 204));

        Arquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/application_double.png"))); // NOI18N
        Arquivo.setText("Arquivo");
        jMenuBar1.add(Arquivo);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jMenu2.setText("Funcionarios");

        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder_user.png"))); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastrar);

        Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder_wrench.png"))); // NOI18N
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        jMenu2.add(Alterar);

        jMenuBar1.add(jMenu2);

        Fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_paste.png"))); // NOI18N
        Fornecedores.setText("Fornecedores");

        cadastrarFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_magnify.png"))); // NOI18N
        cadastrarFornecedores.setText("Cadastrar");
        Fornecedores.add(cadastrarFornecedores);

        alterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_paintbrush.png"))); // NOI18N
        alterarFornecedor.setText("Alterar");
        alterarFornecedor.setToolTipText("");
        alterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFornecedorActionPerformed(evt);
            }
        });
        Fornecedores.add(alterarFornecedor);

        jMenuBar1.add(Fornecedores);

        Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basket.png"))); // NOI18N
        Produtos.setText("Produtos");

        procurarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        procurarProdutos.setText("Procurar");
        Produtos.add(procurarProdutos);

        excluirProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.jpg"))); // NOI18N
        excluirProdutos.setText("Excluir");
        Produtos.add(excluirProdutos);

        jMenuBar1.add(Produtos);

        Relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer_add.png"))); // NOI18N
        Relatorio.setText("Relatorio");

        Days.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock_red.png"))); // NOI18N
        Days.setText("30 Dias");
        Relatorio.add(Days);

        Years.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock.png"))); // NOI18N
        Years.setText("Ultimo Ano");
        Relatorio.add(Years);

        jMenuBar1.add(Relatorio);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarActionPerformed

    private void alterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarFornecedorActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        
        new TelaCadUseSDI().setVisible(true);

        
    }//GEN-LAST:event_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alterar;
    private javax.swing.JMenu Arquivo;
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenuItem Days;
    private javax.swing.JMenu Fornecedores;
    private javax.swing.JMenu Produtos;
    private javax.swing.JMenu Relatorio;
    private javax.swing.JMenuItem Years;
    private javax.swing.JMenuItem alterarFornecedor;
    private javax.swing.JMenuItem cadastrarFornecedores;
    private javax.swing.JMenuItem excluirProdutos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem procurarProdutos;
    // End of variables declaration//GEN-END:variables
}
