/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Meu Computador
 */
public class TelaCadUseSDI extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadUseSDI
     */
    public TelaCadUseSDI() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/icone.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cad1 = new javax.swing.JPanel();
        lblCargo = new javax.swing.JLabel();
        tfCargo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        btContinuar = new javax.swing.JButton();
        tfCPF1 = new javax.swing.JFormattedTextField();
        lblCadastrodeFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionario");
        setMinimumSize(new java.awt.Dimension(650, 390));
        setPreferredSize(new java.awt.Dimension(650, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        Cad1.setBackground(new java.awt.Color(63, 104, 139));
        Cad1.setMinimumSize(new java.awt.Dimension(650, 390));
        Cad1.setPreferredSize(new java.awt.Dimension(650, 390));
        Cad1.setLayout(null);

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblCargo.setText("Cargo");
        Cad1.add(lblCargo);
        lblCargo.setBounds(164, 103, 68, 14);

        tfCargo.setBackground(new java.awt.Color(245, 245, 245));
        tfCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCargoActionPerformed(evt);
            }
        });
        Cad1.add(tfCargo);
        tfCargo.setBounds(149, 117, 213, 24);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");
        Cad1.add(lblNome);
        lblNome.setBounds(164, 154, 68, 14);

        tfNome.setBackground(new java.awt.Color(245, 245, 245));
        Cad1.add(tfNome);
        tfNome.setBounds(149, 167, 213, 24);

        lblCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setText("CPF");
        Cad1.add(lblCPF);
        lblCPF.setBounds(164, 202, 68, 14);

        btContinuar.setBackground(new java.awt.Color(245, 245, 245));
        btContinuar.setText("Continuar");
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });
        Cad1.add(btContinuar);
        btContinuar.setBounds(116, 265, 276, 24);

        tfCPF1.setBackground(new java.awt.Color(245, 245, 245));
        try {
            tfCPF1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPF1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfCPF1.setMinimumSize(new java.awt.Dimension(20, 30));
        tfCPF1.setPreferredSize(new java.awt.Dimension(10, 20));
        tfCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCPF1ActionPerformed(evt);
            }
        });
        Cad1.add(tfCPF1);
        tfCPF1.setBounds(149, 216, 213, 24);

        lblCadastrodeFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblCadastrodeFuncionario.setForeground(new java.awt.Color(245, 245, 245));
        lblCadastrodeFuncionario.setText("Cadastro de funcionário");
        Cad1.add(lblCadastrodeFuncionario);
        lblCadastrodeFuncionario.setBounds(140, 40, 311, 30);

        getContentPane().add(Cad1);
        Cad1.setBounds(-20, -10, 680, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCPF1ActionPerformed

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        Cad1.disable();// Fecha o JFrame atual
        TelaCad2 telaCad2 = new TelaCad2(); // Crie uma nova instância do JFrame desejado
        telaCad2.setVisible(true); // Exibe o novo JFrame
        dispose();

    }//GEN-LAST:event_btContinuarActionPerformed

    private void tfCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadUseSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadUseSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadUseSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadUseSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadUseSDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cad1;
    private javax.swing.JButton btContinuar;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastrodeFuncionario;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JFormattedTextField tfCPF1;
    private javax.swing.JTextField tfCargo;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

}
