/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaCad2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCad2
     */
    public TelaCad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cad2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblCadastroFuncionario = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfSenha = new javax.swing.JLabel();
        ckSenha = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtConfSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        Cad2.setBackground(new java.awt.Color(63, 104, 139));
        Cad2.setLayout(null);

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Cad2.add(jButton1);
        jButton1.setBounds(150, 310, 276, 24);

        lblCadastroFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblCadastroFuncionario.setForeground(new java.awt.Color(242, 242, 242));
        lblCadastroFuncionario.setText("Cadastro de funcionário");
        Cad2.add(lblCadastroFuncionario);
        lblCadastroFuncionario.setBounds(150, 40, 311, 30);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(245, 245, 245));
        lblEmail.setText("Email");
        Cad2.add(lblEmail);
        lblEmail.setBounds(160, 80, 68, 14);

        lblUsuario.setBackground(new java.awt.Color(245, 245, 245));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(245, 245, 245));
        lblUsuario.setText("Usuário");
        Cad2.add(lblUsuario);
        lblUsuario.setBounds(160, 130, 68, 14);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(245, 245, 245));
        lblSenha.setText("Senha");
        Cad2.add(lblSenha);
        lblSenha.setBounds(150, 180, 117, 14);

        lblConfSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfSenha.setForeground(new java.awt.Color(245, 245, 245));
        lblConfSenha.setText("Confirmar senha");
        Cad2.add(lblConfSenha);
        lblConfSenha.setBounds(150, 230, 117, 14);

        ckSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckSenha.setForeground(new java.awt.Color(245, 245, 245));
        ckSenha.setText("Exibir Senha");
        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        Cad2.add(ckSenha);
        ckSenha.setBounds(150, 280, 100, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Cad2.add(jTextField1);
        jTextField1.setBounds(150, 100, 213, 24);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        Cad2.add(jTextField2);
        jTextField2.setBounds(150, 150, 213, 24);

        txtConfSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cad2.add(txtConfSenha);
        txtConfSenha.setBounds(150, 250, 213, 24);

        txtSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cad2.add(txtSenha);
        txtSenha.setBounds(150, 200, 213, 24);

        getContentPane().add(Cad2);
        Cad2.setBounds(-20, -10, 670, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cad2.disable();
        TelaCad3 telaCad3 = new TelaCad3();
        telaCad3.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
    if (ckSenha.isSelected()){
            txtSenha.setEchoChar((char)0);
            txtConfSenha.setEchoChar((char)0);
        }else{
        txtSenha.setEchoChar('*');
        txtConfSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_ckSenhaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCad2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cad2;
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCadastroFuncionario;
    private javax.swing.JLabel lblConfSenha;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtConfSenha;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
