/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.JobAttributes;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaCad3 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCad3
     */
    public TelaCad3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cad3 = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCEP = new javax.swing.JLabel();
        lblCidadeeEstado = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 390));
        setResizable(false);

        Cad3.setBackground(new java.awt.Color(63, 104, 139));
        Cad3.setPreferredSize(new java.awt.Dimension(530, 310));
        Cad3.setLayout(null);

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(245, 245, 245));
        lblEndereco.setText("Endereço");
        Cad3.add(lblEndereco);
        lblEndereco.setBounds(162, 85, 68, 14);

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(245, 245, 245));
        lblNumero.setText("Número");
        Cad3.add(lblNumero);
        lblNumero.setBounds(162, 132, 68, 14);

        lblCEP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCEP.setForeground(new java.awt.Color(245, 245, 245));
        lblCEP.setText("CEP");
        Cad3.add(lblCEP);
        lblCEP.setBounds(162, 231, 117, 14);

        lblCidadeeEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCidadeeEstado.setForeground(new java.awt.Color(245, 245, 245));
        lblCidadeeEstado.setText("Cidade e Estado");
        Cad3.add(lblCidadeeEstado);
        lblCidadeeEstado.setBounds(162, 278, 117, 16);

        lblComplemento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(245, 245, 245));
        lblComplemento.setText("Complemento");
        Cad3.add(lblComplemento);
        lblComplemento.setBounds(162, 184, 117, 14);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 245, 245));
        jLabel6.setText("Cadastro de funcionário");
        Cad3.add(jLabel6);
        jLabel6.setBounds(160, 40, 311, 30);

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        Cad3.add(btCadastrar);
        btCadastrar.setBounds(116, 343, 276, 24);
        Cad3.add(jTextField1);
        jTextField1.setBounds(147, 99, 213, 24);
        Cad3.add(jTextField2);
        jTextField2.setBounds(147, 146, 213, 24);

        jTextField3.setToolTipText("");
        Cad3.add(jTextField3);
        jTextField3.setBounds(147, 198, 213, 24);
        Cad3.add(jTextField4);
        jTextField4.setBounds(147, 245, 213, 24);
        Cad3.add(jTextField5);
        jTextField5.setBounds(147, 292, 213, 24);

        jCheckBox1.setForeground(new java.awt.Color(245, 245, 245));
        jCheckBox1.setText("Admnistrador");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Cad3.add(jCheckBox1);
        jCheckBox1.setBounds(150, 320, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cad3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cad3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
     
        JOptionPane.showMessageDialog(null, "Usuario Cadastrado");
        dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCad3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cad3;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCidadeeEstado;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNumero;
    // End of variables declaration//GEN-END:variables
}
