/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Meu Computador
 */
public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastrodadosUsuario
     */
    public CadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDescricao = new javax.swing.JLabel();
        lbQTD = new javax.swing.JLabel();
        lbPRECO = new javax.swing.JLabel();
        tfDESCRICAO = new javax.swing.JTextField();
        tfQTD = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPRODUTOS = new javax.swing.JTable();
        tfPRECO = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btClose = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        lbDescricao.setText("DESCRIÇÃO");

        lbQTD.setText("QTD");

        lbPRECO.setText("PREÇO");

        tfQTD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        jtPRODUTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DESCRIÇÃO", "QTD", "PREÇO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPRODUTOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPRODUTOSMouseClicked(evt);
            }
        });
        jtPRODUTOS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPRODUTOSKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtPRODUTOS);

        tfPRECO.setText("R$ ");
        tfPRECO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPRECOActionPerformed(evt);
            }
        });
        tfPRECO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPRECOKeyPressed(evt);
            }
        });

        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jButton1.setText("ATUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btClose.setText("FECHAR");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(btExcluir))
                            .addComponent(tfDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescricao))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btClose))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfQTD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbQTD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPRECO)
                                    .addComponent(tfPRECO, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescricao)
                    .addComponent(lbQTD)
                    .addComponent(lbPRECO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPRECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btExcluir)
                    .addComponent(jButton1)
                    .addComponent(btClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 663, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed

        DefaultTableModel btmPRODUTOS = (DefaultTableModel)jtPRODUTOS.getModel();
        Object [] dados = {tfDESCRICAO.getText(),tfQTD.getText(),tfPRECO.getText()};
        btmPRODUTOS.addRow(dados);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void jtPRODUTOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPRODUTOSMouseClicked

        if(jtPRODUTOS.getSelectedRow() != -1){

            lbDescricao.setText(jtPRODUTOS.getValueAt(jtPRODUTOS.getSelectedRow(), 0).toString());
            lbQTD.setText(jtPRODUTOS.getValueAt(jtPRODUTOS.getSelectedRow(), 1).toString());
            lbPRECO.setText(jtPRODUTOS.getValueAt(jtPRODUTOS.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_jtPRODUTOSMouseClicked

    private void jtPRODUTOSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPRODUTOSKeyReleased
        // TODO add your handling code here:
        if(jtPRODUTOS.getSelectedRow() != -1){

            lbDescricao.setText(jtPRODUTOS.getValueAt(jtPRODUTOS.getSelectedRow(), 0).toString());
            lbQTD.setText(jtPRODUTOS.getValueAt(jtPRODUTOS.getSelectedRow(), 1).toString());
            lbPRECO.setText(jtPRODUTOS.getValueAt(jtPRODUTOS.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_jtPRODUTOSKeyReleased

    private void tfPRECOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPRECOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPRECOActionPerformed

    private void tfPRECOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPRECOKeyPressed
        //Comando para quando pressionar a tecla enter
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            DefaultTableModel btmPRODUTOS = (DefaultTableModel)jtPRODUTOS.getModel();
            Object [] dados = {tfDESCRICAO.getText(),tfQTD.getText(),tfPRECO.getText()};
            btmPRODUTOS.addRow(dados);
        }
    }//GEN-LAST:event_tfPRECOKeyPressed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        if(jtPRODUTOS.getSelectedRow() != -1){

            //jtPRODUTOS.getSelectedRow();
            DefaultTableModel btmPRODUTOS = (DefaultTableModel)jtPRODUTOS.getModel();
            btmPRODUTOS.removeRow(jtPRODUTOS.getSelectedRow());
        } else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jtPRODUTOS.getSelectedRow() != -1){

            jtPRODUTOS.setValueAt(lbDescricao.getText(), jtPRODUTOS.getSelectedRow(), 0);
            jtPRODUTOS.setValueAt(lbQTD.getText(), jtPRODUTOS.getSelectedRow(), 1);
            jtPRODUTOS.setValueAt(lbPRECO.getText(), jtPRODUTOS.getSelectedRow(), 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
       dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JToggleButton btClose;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPRODUTOS;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbPRECO;
    private javax.swing.JLabel lbQTD;
    private javax.swing.JTextField tfDESCRICAO;
    private javax.swing.JTextField tfPRECO;
    private javax.swing.JTextField tfQTD;
    // End of variables declaration//GEN-END:variables
}
