package telas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class Index extends javax.swing.JFrame {

    public Index() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/icon_LogoAgro.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblEmail = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JFormattedTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        BtnPassword = new javax.swing.JButton();
        ckSenha = new javax.swing.JCheckBox();
        img_LogoAgro = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        fundo1 = new javax.swing.JLabel();
        fundo2 = new javax.swing.JLabel();
        fundo3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AgroCultiva Soluções");
        setMinimumSize(new java.awt.Dimension(650, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(390, 130, 40, 16);

        txtUsuario.setBackground(new java.awt.Color(245, 245, 245));
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setMinimumSize(new java.awt.Dimension(20, 30));
        txtUsuario.setPreferredSize(new java.awt.Dimension(10, 20));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(390, 150, 200, 30);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(390, 190, 60, 16);

        txtSenha.setBackground(new java.awt.Color(245, 245, 245));
        txtSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(390, 210, 200, 30);

        BtnPassword.setBackground(new java.awt.Color(245, 245, 245));
        BtnPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPassword.setText("Enviar");
        BtnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPassword);
        BtnPassword.setBounds(400, 280, 140, 33);

        ckSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckSenha.setForeground(new java.awt.Color(242, 242, 242));
        ckSenha.setText("Exibir Senha");
        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ckSenha);
        ckSenha.setBounds(410, 250, 100, 20);

        img_LogoAgro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agrocultiva_Orquídea___1_-removebg-preview.png"))); // NOI18N
        getContentPane().add(img_LogoAgro);
        img_LogoAgro.setBounds(-100, 40, 390, 280);

        lblSubTitulo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblSubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitulo.setText("Digite seus dados de acesso no campo abaixo.");
        getContentPane().add(lblSubTitulo);
        lblSubTitulo.setBounds(330, 80, 290, 30);

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("                    Boas vindas!");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(340, 30, 240, 60);

        fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ciano degrade.png"))); // NOI18N
        getContentPane().add(fundo1);
        fundo1.setBounds(300, -100, 340, 660);

        fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/branco neve.png"))); // NOI18N
        getContentPane().add(fundo2);
        fundo2.setBounds(0, 60, 300, 340);

        fundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/branco neve.png"))); // NOI18N
        getContentPane().add(fundo3);
        fundo3.setBounds(0, 0, 300, 100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void BtnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPasswordActionPerformed
        // TODO add your handling code here:
        String login,senha;
        
        
        login = txtUsuario.getText();
        senha = txtSenha.getText();
        
        if("adm".equals(login) && "adm".equals(senha))
        {
        JOptionPane.showMessageDialog(null, "Seja bem vindo!!!");
        abrirTelaMenu();
        }
        else{
            JOptionPane.showMessageDialog(null, "Fatal Error.Usuario não encontrado");
        }
}
    public void abrirTelaMenu()
    {
    dispose();

    TelaMenu telaMenu = new TelaMenu();
    telaMenu.setVisible(true);
    }//GEN-LAST:event_BtnPasswordActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
        if (ckSenha.isSelected()){
            txtSenha.setEchoChar((char)0);
        }else{
        txtSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_ckSenhaActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        if(txtUsuario.getText().equals("adm") && txtSenha.getText().equals("adm")){
        
        JOptionPane.showMessageDialog(null, "Bem vindo!!");
        abrirTelaMenu();
        } else {
        JOptionPane.showMessageDialog(null, "Fatal Error.Usuario não encontrado");
        }
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPassword;
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JLabel fundo1;
    private javax.swing.JLabel fundo2;
    private javax.swing.JLabel fundo3;
    private javax.swing.JLabel img_LogoAgro;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
